export const ActionTypes = {
  RANDOM_CHARACTERS_SUCCESS: 'RANDOM_CHARACTERS_SUCCESS',
  RANDOM_CHARACTERS_FAIL: 'RANDOM_CHARACTERS_FAIL',
  GET_CODE_SUCCESS: 'GET_CODE_SUCCESS',
  GET_CODE_FAIL: 'GET_CODE_FAIL',
  CHARACTERS_EDIT_SUCCESS: 'CHARACTERS_EDIT_SUCCESS',
  CHARACTERS_EDIT_FAIL: 'CHARACTERS_EDIT_FAIL'
};
